cache fixes

diff --git a/.github/workflows/task-rust-tests.yml b/.github/workflows/task-rust-tests.yml
--- a/.github/workflows/task-rust-tests.yml
+++ b/.github/workflows/task-rust-tests.yml
@@ -13,33 +13,8 @@ on:
   workflow_call:
 
 jobs:
-  setup:
-    runs-on: ubuntu-latest
-    outputs:
-      node_changed: ${{ steps.node_check.outputs.changed }}
-    env:
-      SKIP_BUILD_LABEL_PRESENT: ${{ contains(github.event.pull_request.labels.*.name, 'skip-node-build') }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Check if Substrate Node needs rebuild
-        id: node_check
-        run: |
-          BASE_SHA="${{ github.event.pull_request.base.sha || github.event.before }}"
-          HEAD_SHA="${{ github.sha }}"
-
-          if [[ "${{ env.SKIP_BUILD_LABEL_PRESENT }}" != "true" ]] && git diff --name-only $BASE_SHA $HEAD_SHA | grep -E '^operator/(client|node|pallets|runtime)/|^operator/Cargo\.toml$'; then
-            echo "changed=true" >> $GITHUB_OUTPUT
-          else
-            echo "Comparing changes from $BASE_SHA to $HEAD_SHA"
-            echo "changed=false" >> $GITHUB_OUTPUT
-          fi
 
   prepare:
-    needs: [setup]
-    if: needs.setup.outputs.node_changed == 'true'
     name: Prepare artifacts for Rust tests
     runs-on: ubuntu-latest
     env:
@@ -53,19 +28,14 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
-          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Run sccache-cache
-        uses: mozilla-actions/sccache-action@v0.0.9
+          submodules: recursive
+          fetch-depth: 0
+      - uses: ./.github/workflows/actions/setup-rust
+        with:
+          cache-key: "TEST"
       - uses: rui314/setup-mold@v1
       - name: Install nextest
         uses: taiki-e/install-action@nextest
-      # Install libpq-dev
-      - name: Install libpq-dev
-        run: sudo apt-get update && sudo apt-get install -y libpq-dev
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v3
       - name: Build and archive tests
         run: cargo nextest archive --archive-file nextest-archive.tar.zst
       - name: Upload archive to workflow
@@ -75,8 +45,6 @@ jobs:
           path: ./operator/nextest-archive.tar.zst
 
   all-rust-tests:
-    needs: [setup, prepare]
-    if: needs.setup.outputs.node_changed == 'true'
     name: Run all Operator Rust tests (/w partitioning)
     runs-on: ubuntu-latest
     strategy:
@@ -104,22 +72,17 @@ jobs:
 
   tests-result-checker:
     name: Check tests were successful
-    needs: [setup, all-rust-tests]
-    if: always()
+    needs: [all-rust-tests]
     runs-on: ubuntu-latest
     steps:
       - name: Validate test results
         run: |
-          echo "node_changed: ${{ needs.setup.outputs.node_changed }}"
           echo "matrix result: ${{ needs.all-rust-tests.result }}"
 
-          if [ "${{ needs.setup.outputs.node_changed }}" == "true" ]; then
-            if [ "${{ needs.all-rust-tests.result }}" != "success" ]; then
-              echo "Rust tests failed or were cancelled"
-              exit 1
-            else
-              echo "Rust tests passed"
-            fi
+          if [ "${{ needs.all-rust-tests.result }}" != "success" ]; then
+            echo "Rust tests failed or were cancelled"
+            exit 1
           else
-            echo "No relevant changes — skipping rust tests"
+            echo "Rust tests passed"
           fi
+
